name: Build and Deploy

on:
  push:
    branches:
      - "master"
      - "Morl99/issue3" # FIXME remove after testing 

jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: action/checkout@2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}